# Generated by Django 5.2.14 on 2026-05-19 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('robot_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('robot_type', models.CharField(max_length=100)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('operational_status', models.CharField(max_length=50)),
                ('max_payload_kg', models.FloatField(blank=True, null=True)),
                ('max_speed_mps', models.FloatField(blank=True, null=True)),
                ('battery_capacity_wh', models.FloatField(blank=True, null=True)),
                ('total_operational_hours', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(max_length=100)),
                ('area_sqm', models.FloatField(blank=True, null=True)),
                ('capacity_units', models.IntegerField(blank=True, null=True)),
                ('current_occupancy_pct', models.FloatField(blank=True, null=True)),
                ('zone_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('log_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('technician_id', models.CharField(max_length=50)),
                ('maintenance_date', models.DateField(blank=True, null=True)),
                ('maintenance_type', models.CharField(max_length=50)),
                ('duration_hours', models.FloatField(blank=True, null=True)),
                ('parts_replaced', models.TextField(blank=True, null=True)),
                ('total_cost_usd', models.FloatField(blank=True, null=True)),
                ('downtime_hours', models.FloatField(blank=True, null=True)),
                ('completion_status', models.CharField(max_length=50)),
                ('recurrence_count', models.IntegerField(default=0)),
                ('inspection_passed', models.IntegerField(default=1)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='dashboard.robot')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('task_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task_type', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('items_count', models.IntegerField(blank=True, null=True)),
                ('distance_m', models.FloatField(blank=True, null=True)),
                ('time_taken_min', models.FloatField(blank=True, null=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dashboard.robot')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dashboard.zone')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('reading_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sensor_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('reading_type', models.CharField(max_length=50)),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(max_length=20)),
                ('alert_triggered', models.IntegerField(default=0)),
                ('alert_level', models.CharField(blank=True, max_length=50, null=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='dashboard.robot')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='dashboard.zone')),
            ],
        ),
    ]
